# Generated by Django 4.1.7 on 2023-03-29 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0002_alter_servicio_options_alter_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_jugados', models.IntegerField(null=True)),
                ('minimo', models.IntegerField(null=True)),
                ('maximo', models.IntegerField(null=True)),
                ('repeticion_niveles', models.IntegerField(null=True)),
                ('engranes', models.IntegerField(null=True)),
                ('duracion_promedio', models.IntegerField(null=True)),
                ('success_promedio', models.IntegerField(null=True)),
                ('a_que_nivel_llego', models.IntegerField(null=True)),
                ('sesion_iniciada_dia', models.IntegerField(null=True)),
                ('sesion_iniciada_mes', models.IntegerField(null=True)),
                ('id_de_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
