# Generated by Django 4.1.7 on 2023-05-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_producto_created_producto_uodated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={'verbose_name': 'CategoriaProd', 'verbose_name_plural': 'CategoriasProd'},
        ),
        migrations.RenameField(
            model_name='categoriaprod',
            old_name='uodated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='uodated',
            new_name='updated',
        ),
    ]
